version: '3'

services:
  api:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
  db:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .db:/database
