version: '3'

services:
  db:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .db:/database/rd
    expose:
      - "6379"

  pgdb:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PG_PWD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - .db:/database/pg
    expose:
      - "5432"
